name: av
dependencies:
  - python
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch 
    - torchvision  
    - torchaudio  
    - opencv-python
    - soundfile
    - scipy
    - pypesq
    - pystoi
    - thop
    - timm
    - pytorch-lightning
    - torch-optimizer
    - omegaconf
    - tensorboard
    - black