# Video network config
videonet:
    backbone_type: resnet
    relu_type: prelu
    width_mult: 1.0
    pretrain: ../pretrain_zoo/frcnn_128_512.backbone.pth.tar
audionet:
    n_src: 1
    pretrained_vout_chan: 512                  # output from pretrained model

    gc3_params:
      audio:
        group_size: 1                          # 128/8=16, 512/16=32
        context_size: 1                       # 128/32=4, 512/4=128
      video:    
        group_size: 1                          # 128/8=16, 64/16=4
        context_size: 1                       # 128/32=4, 64/4=16 

    video_bn_params:
      out_chan: 64
      kernel_size: 3
      padding: 1

    audio_bn_params:
      out_chan: 64
      kernel_size: 1
      is2d: True

    enc_dec_params:
      encoder_type: STFTEncoder
      decoder_type: STFTDecoder
      win: 256
      hop_length: 128
      out_chan: 512
      kernel_size: 3
      stride: 1
      bias: False
      act_type: 
      norm_type: gLN
      
    audio_params:
      audio_net: TDANet
      # in_chan same as audio_bn_chan
      hid_chan: 128                       # TDANet hidden channels
      upsampling_depth: 5
      shared: True
      repeats: 4
      norm_type: gLN
      act_type: PReLU
      kernel_size: 5
      stride: 2 
      n_head: 8
      is2d: True
    
    video_params:
      video_net: TDANet
      # in_chan same as video_bn_chan
      hid_chan: 64
      upsampling_depth: 4
      shared: True
      repeats: 1
      norm_type: BatchNorm2d
      act_type: PReLU
      kernel_size: 3
      stride: 2
      n_head: 8
      is2d: True

    fusion_params:
      fusion_type: ConcatFusion
      fusion_shared: True
      is2d: True

    mask_generation_params:
      mask_act: ReLU
      is2d: True
      
# Training config
training:
    gpus: [0,1,2,3,4,5,6]
    epochs: 200
    batch_size: 4
    num_workers: 8
    half_lr: yes
    early_stop: yes
    divide_lr_by: null
    online_mix: false
# Optim config
optim:
    optimizer: adamw
    lr: 0.001
    weight_decay: 0.1
# Sche config
sche:
    patience: 49
    factor: 0.5
# Data config
data:
    train_dir: data-preprocess/LRS2/tr
    valid_dir: data-preprocess/LRS2/cv
    nondefault_nsrc: 1
    sample_rate: 16000
    segment: 2.0
    normalize_audio: false
log:
    path: log/tmp
    pro_name: project
    exp_name: ctcnet_small_tdanet2d_08_03_2023
