# Video network config
videonet:
    model_name: FRCNNVideoModel
    backbone_type: resnet
    relu_type: prelu
    width_mult: 1.0
    pretrain: ../pretrain_zoo/frcnn_128_512.backbone.pth.tar
audionet:
    n_src: 1
    pretrained_vout_chan: 512                  # output from pretrained model
    concat_first: True

    video_bn_params:
      kernel_size: -1

    audio_bn_params:
      out_chan: 32
      kernel_size: 1
      is2d: True

    enc_dec_params:
      encoder_type: STFTEncoder
      decoder_type: STFTDecoder
      win: 512
      hop_length: 128
      out_chan: 32
      kernel_size: 3
      stride: 1
      bias: False
      act_type: ReLU
      norm_type: gLN
      
    audio_params:
      audio_net: TDAVNet
      # in_chan same as audio_bn_chan
      hid_chan: 32
      kernel_size: 5
      stride: 2 
      norm_type: gLN
      act_type: PReLU
      upsampling_depth: 5
      repeats: 4
      shared: True
      rnn_1_conf:
        hid_chan: 256
        dim: 3
        kernel_size: 8
        stride: 1
        rnn_type: GRU
        bidirectional: True
      rnn_2_conf:
        hid_chan: 256
        dim: 4
        kernel_size: 8
        stride: 1
        rnn_type: GRU
        bidirectional: True
      attention_conf:
        n_freqs: 17
        n_head: 4
        hid_chan: 4
        act_type: PReLU
        norm_type: LayerNormalization4D

    video_params:
      video_net: TDANet
      # in_chan same as video_bn_chan
      hid_chan: 64
      upsampling_depth: 4
      shared: True
      repeats: 1
      norm_type: BatchNorm1d
      act_type: PReLU
      kernel_size: 3
      stride: 2
      is2d: False
      attention_params:
        attention_type: GlobalAttention
        ffn_name: FeedForwardNetwork
        kernel_size: 3
        n_head: 8
        dropout: 0.1

    fusion_params:
      fusion_type: ConcatFusion
      fusion_shared: True
      is2d: True
      nstack: False

    mask_generation_params:
      mask_act: ReLU
      is2d: True
      output_gate: True
      
# Training config
training:
    gpus: [0,1,2,3,4,5,6,7]
    epochs: 200
    batch_size: 8
    num_workers: 8
    half_lr: yes
    early_stop: yes
    divide_lr_by: null
    online_mix: false
# Optim config
optim:
    optimizer: adamw
    lr: 0.001
    weight_decay: 0.1
# Sche config
sche:
    patience: 49
    factor: 0.5
# Data config
data:
    train_dir: data-preprocess/LRS2/tr
    valid_dir: data-preprocess/LRS2/cv
    nondefault_nsrc: 1
    sample_rate: 16000
    segment: 2.0
    normalize_audio: false
log:
    path: log/tmp
    pro_name: project
    exp_name: avnet_mini/gridnet/01_07_23_GRU
