# Video network config
videonet:
    backbone_type: resnet
    relu_type: prelu
    width_mult: 1.0
    pretrain: ../pretrain_zoo/frcnn_128_512.backbone.pth.tar
audionet:
  act_type: PReLU
  audio_bn_chan: 512
  audio_net: FRCNN
  audio_repeats: 3
  audio_shared: true
  fusion_repeats: 1
  fusion_shared: true
  fusion_type: ConcatFusion
  hid_chan: 512
  in_chan: 512
  kernel_size: 21
  mask_act: ReLU
  n_src: 1
  norm_type: gLN
  stride: 10
  upsampling_depth: 5
  video_params:
    act_type: PReLU
    hid_chan: 64
    in_chan: 64
    kernel_size: 3
    norm_type: BatchNorm1d
    shared: true
    stride: 2
    upsampling_depth: 4
    video_net: FRCNN
    vout_chan: 512
# Training config
training:
    gpus: [0,1,2,3,4,5,6]
    epochs: 200
    batch_size: 4
    num_workers: 8
    half_lr: yes
    early_stop: yes
    divide_lr_by: null
    online_mix: false
# Optim config
optim:
    optimizer: adamw
    lr: 0.001
    weight_decay: 0.1
# Sche config
sche:
    patience: 49
    factor: 0.5
# Data config
data:
    train_dir: data-preprocess/LRS2/tr
    valid_dir: data-preprocess/LRS2/cv
    nondefault_nsrc: 1
    sample_rate: 16000
    segment: 2.0
    normalize_audio: false
log:
    path: log/tmp
    pro_name: project
    exp_name: ctcnet_small_frcnn_21_02_23