# Video network config
videonet:
    backbone_type: resnet
    relu_type: prelu
    width_mult: 1.0
    pretrain: ../pretrain_zoo/frcnn_128_512.backbone.pth.tar
audionet:
    audio_net: TDANet
    n_src: 1
    in_chan: 512
    kernel_size: 21
    stride: 10
    hid_chan: 256                       # FRCNN hidden channels
    audio_bn_chan: 128                  # bottleneck
    fusion_repeats: 1
    audio_repeats: 3
    mask_act: ReLU
    act_type: PReLU
    norm_type: gLN
    # video frcnn
    video_params:
        video_net: TDANet
        vout_chan: 512                  # output from pretrained model
        in_chan: 64                     # video bottleneck 
        hid_chan: 64
        upsampling_depth: 5
        shared: False
        kernel_size: 5
# Training config
training:
    gpus: [0,1,2,3,4,5,6,7]
    epochs: 200
    batch_size: 4
    num_workers: 8
    half_lr: yes
    early_stop: yes
    divide_lr_by: null
    online_mix: false
# Optim config
optim:
    optimizer: adamw
    lr: 0.001
    weight_decay: 0.1
# Sche config
sche:
    patience: 49
    factor: 0.5
# Data config
data:
    train_dir: data-preprocess/LRS2/tr
    valid_dir: data-preprocess/LRS2/cv
    nondefault_nsrc: 1
    sample_rate: 16000
    segment: 2.0
    normalize_audio: false
log:
    path: log/tmp
    pro_name: project
    exp_name: ctcnet_pretrain_1_3_bn128_hid256_31_1_2023