# Video network config
videonet:
    backbone_type: resnet
    relu_type: prelu
    width_mult: 1.0
    pretrain: ../../pretrain_zoo/lrw_resnet18_mstcn_adamw_s3.pth.tar
audionet:
    # sample_rate: 16000
    # filterbank
    n_filters: 512
    kernel_size: 21
    stride: 10
    # masknet
    n_src: 1
    n_blocks: 8
    an_repeats: 8
    fn_repeats: 0
    mask_act: relu
    act_type: prelu
    norm_type: gLN
    bn_chan: 512
    hid_chan: 512
    # video
    vin_chan: 512
    vout_chan: 512
    vconv_kernel_size: 3
    vn_repeats: 5
    # fusion
    fout_chan: 512
    # video frcnn
    video_frcnn:
        in_chan: 128
        out_chan: 128
        depth: 4
        iter: 8
        shared: False
        norm_type: "BatchNorm1d"
        act_type: "PReLU"
        kernel_size: 3
    # pretrain: ../../pretrain_zoo/frcnn_128_512.pth.tar
# Training config
training:
    epochs: 200
    batch_size: 3
    num_workers: 8
    half_lr: yes
    early_stop: yes
    divide_lr_by: null
    online_mix: false
# Optim config
optim:
    optimizer: adamw
    lr: 0.001
    weight_decay: 0.1
# Sche config
sche:
    patience: 49
    factor: 0.5
# Data config
data:
    train_dir: local/data/tr/
    valid_dir: local/data/cv/
    nondefault_nsrc: 1
    sample_rate: 16000
    segment: 2.0
    normalize_audio: false
log:
    path: log/tmp
    pro_name: nichang_avproject
    exp_name: frcnn2_128_128_3_adamw_1e-1_r8